# Generated by Django 6.0.4 on 2026-04-29 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exhibit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "approximate_year",
                    models.CharField(
                        blank=True,
                        help_text="Например: 1943, 1970-е, начало XX века",
                        max_length=100,
                        verbose_name="Примерный год",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Например: самолёт, жетон, фляга, костюм",
                        max_length=100,
                        verbose_name="Тип экспоната",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Экспонат",
                "verbose_name_plural": "Экспонаты",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ExhibitImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="exhibits/", verbose_name="Изображение"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "exhibit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="collection.exhibit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография экспоната",
                "verbose_name_plural": "Фотографии экспонатов",
                "ordering": ["order", "id"],
            },
        ),
    ]
