# Generated by Django 6.0.4 on 2026-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MuseumInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Музей школы 22",
                        max_length=200,
                        verbose_name="Название музея",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание музея"),
                ),
            ],
            options={
                "verbose_name": "Информация о музее",
                "verbose_name_plural": "Информация о музее",
            },
        ),
    ]
